project/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('social.urls')),
    path('accounts/', include('users.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

social/urls.py
from django.urls import path
from social.views import (
    tweet_page,
    PostListView,
    PostDetailView,
    PostUpdateView,
    PostDeleteView,
    CommentUpdateView,
    CommentDeleteView,
    AddFollowView,
    RemoveFollowView,
    AddLikeView,
    AddDislikeView,
    UserFollowersView,
    CommentLikeView,
    CommentDislikeView,
    CommentReplyView,
    PostNotificationsView,
    FollowNotificationsView,
    ListThreadsView,
    CreateThreadView,
    ThreadView,
    CreateMessageView,
    ThreadNotificationView
)

urlpatterns = [
    path('', PostListView.as_view(), name="home_page"),
    path('tweet', tweet_page, name="tweet_page"),
    path('post/<int:pk>/', PostDetailView.as_view(), name="post_detail"),

    path('post/<int:pk>/like/', AddLikeView.as_view(), name="post_like"),
    path('post/<int:pk>/dislike/', AddDislikeView.as_view(), name="post_dislike"),

    path('post/update/<int:pk>/', PostUpdateView.as_view(), name="post_update"),
    path('post/delete/<int:pk>/', PostDeleteView.as_view(), name="post_delete"),

    path('post/<int:post_pk>/comment_update/<int:pk>/', CommentUpdateView.as_view(), name="comment_update"),
    path('post/<int:post_pk>/comment_delete/<int:pk>/', CommentDeleteView.as_view(), name="comment_delete"),

    path('post/<int:post_pk>/comment/<int:pk>/like/', CommentLikeView.as_view(), name="comment_like"),
    path('post/<int:post_pk>/comment/<int:pk>/dislike/', CommentDislikeView.as_view(), name="comment_dislike"),

    path('post/<int:post_pk>/comment/<int:pk>/reply/', CommentReplyView.as_view(), name="comment_reply"),

    path('profile/<int:pk>/followers/', UserFollowersView.as_view(), name="user_followers"),
    path('profile/<int:pk>/followers/add/', AddFollowView.as_view(), name="add_follow"),
    path('profile/<int:pk>/followers/remove/', RemoveFollowView.as_view(), name="remove_follow"),


    path(
        'notification/<int:notification_pk>/post/<int:post_pk>/',
        PostNotificationsView.as_view(),
        name="post_notification"
    ),

    path(
        'notification/<int:notification_pk>/post/<int:post_pk>/',
        FollowNotificationsView.as_view(),
        name="follow_notification"
    ),

    path(
        'notification/<int:notification_pk>/thread/<int:thread_pk>/',
        ThreadNotificationView.as_view(),
        name="thread_notification"
    ),

    path('inbox/', ListThreadsView.as_view(), name="inbox"),
    path('inbox/create_thread/', CreateThreadView.as_view(), name="create_thread"),
    path('inbox/<int:pk>/', ThreadView.as_view(), name="thread"),
    path('inbox/<int:pk>/create_message/', CreateMessageView.as_view(), name="create_message"),
]

users/urls.py
from django.urls import path
from users.views import registration_page, User_Signup_View, User_Signin_View, User_Signout_View, UserProfileView, EditUserProfile, UserSearchView


urlpatterns = [
	path('', registration_page, name="user_registration_page"),
    path('register/', User_Signup_View.as_view(), name="user_signup_page"),
    path('login/', User_Signin_View.as_view(), name="user_signin_page"),
    path('logout/', User_Signout_View.as_view(), name="user_signout_page"),
    path('search_results/', UserSearchView.as_view(), name="search_results"),
    path('profile/<int:pk>/', UserProfileView.as_view(), name="user_profile"),
	path('profile/edit/<int:pk>/', EditUserProfile.as_view(), name="edit_user_profile"),
]

social/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

# Create your models here.
class Post(models.Model):
    body = models.TextField()
    post_image = models.ManyToManyField('PostImage', blank=True)
    created_on = models.DateTimeField(default=timezone.now)  # Set The Time When You Hit The Submit Btn.
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='post_author')
    likes = models.ManyToManyField(User, blank=True, related_name='likes')
    dislikes = models.ManyToManyField(User, blank=True, related_name='dislikes')
    tags = models.ManyToManyField('Tag', blank=True)

    # handle tags
    def create_tags(self):
        # loop through every word inside the post body field
        for word in self.body.split():
            # if the first of any word inside the body contains '#'  >> This is #body
            if word[0] == '#':
                # the tag word starts from the first letter after '#' to the end of it , generally the second letter
                tag = Tag.objects.filter(name=word[1:])
                # if there're written tags in the post body
                if tag:
                    # add that tag(s) to the tags list
                    self.tags.add(tag.pk)
                # if there's no tag(s)
                else:
                    tag = Tag(name=word[1:])
                    tag.save()
                    self.tags.add(tag.pk)
                # Save the Post
                self.save()


class PostImage(models.Model):
    post_image = models.ImageField(upload_to='post_image/', null=True, blank=True)


class Tag(models.Model):
    name = models.CharField(max_length=50, blank=True, null=True)


class Comment(models.Model):
    comment = models.TextField()
    created_on = models.DateTimeField(default=timezone.now)
    commentator = models.ForeignKey(User, on_delete=models.CASCADE, related_name='post_commentator')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='commented_post')
    likes = models.ManyToManyField(User, blank=True, related_name='comment_likes')
    dislikes = models.ManyToManyField(User, blank=True, related_name='comment_dislikes')
    parent = models.ForeignKey('self', on_delete=models.CASCADE, blank=True, null=True, related_name='+')

    @property
    def children(self):
        return Comment.objects.filter(parent=self).all()

    @property
    def is_parent(self):
        if self.parent is None:
            return True
        return False


class Notification(models.Model):
    notification_type = models.IntegerField()  # 1 == Like , 2 == Comment , 3 == Follow , 4 == DM
    to_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='notification_to', null=True)
    from_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='notification_from', null=True)
    post = models.ForeignKey('Post', on_delete=models.CASCADE, related_name='+', null=True)
    comment = models.ForeignKey('Comment', on_delete=models.CASCADE, related_name='+', null=True)
    thread = models.ForeignKey('ThreadModel', on_delete=models.CASCADE, related_name='+', null=True, blank=True)
    date = models.DateTimeField(default=timezone.now)
    user_has_seen = models.BooleanField(default=False)


class ThreadModel(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='+')
    receiver = models.ForeignKey(User, on_delete=models.CASCADE, related_name='+')


class MessageModel(models.Model):
    thread = models.ForeignKey(ThreadModel, on_delete=models.CASCADE, related_name='+', null=True, blank=True)
    sender_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='+')
    receiver_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='+')
    body = models.CharField(max_length= 250)
    img = models.ImageField(upload_to='message/', null=True, blank=True)
    date = models.DateTimeField(default=timezone.now)
    is_read = models.BooleanField(default=False)

social/forms.py
from django import forms
from social.models import Post, Comment, MessageModel


class AddPostForm(forms.ModelForm):
    body = forms.CharField(
        label='',
        widget=forms.Textarea(
            attrs={
                'class': 'post-input',
                'placeholder': 'Say Something ...'
            }
        )
    )

    # post_image = forms.ImageField(required=False, label='')
    post_image = forms.ImageField(
        required=False,
        label='',
        widget=forms.ClearableFileInput(
            attrs={
                'class': 'upload-post-file',
                'multiple': True,
            }
        )
    )   # not to raise an error while submitting the post form that has no image

    class Meta:
        model = Post
        fields = ['body', 'post_image']


class AddCommentForm(forms.ModelForm):
    comment = forms.CharField(
        label='',
        widget=forms.Textarea(
            attrs={
                'rows': 3,
                'placeholder': 'Write a Comment ...'
            }
        )
    )

    class Meta:
        model = Comment
        fields = ['comment']


class ThreadForm(forms.Form):
    username = forms.CharField(label='', max_length=100)


class MessageForm(forms.ModelForm):
    body = forms.CharField(label='', max_length=220)
    img = forms.ImageField(required=False, label='')

    class Meta:
        model = MessageModel
        fields = ['body', 'img']

users/forms.py
from django import forms
from django.contrib.auth.models import User
from users.models import Profile
from django.contrib.auth import authenticate


class User_Signup_Form(forms.Form):
    username= forms.CharField(label= '', widget=forms.TextInput(attrs={"class": "input-field", 'placeholder': 'John Doe'}))
    email= forms.EmailField(label= '', widget=forms.EmailInput(attrs={"class": "input-field", 'placeholder': 'johndoe@gmail.com'}))
    first_name= forms.CharField(label= '', widget=forms.TextInput(attrs={"class": "input-field", 'placeholder': 'John'}))
    last_name= forms.CharField(label= '', widget=forms.TextInput(attrs={"class": "input-field", 'placeholder': 'Doe'}))
    password= forms.CharField(label= '', widget=forms.PasswordInput(attrs={ "class": "input-field", 'placeholder': 'Password'}))
    password_confirmation= forms.CharField(label= '', widget=forms.PasswordInput(attrs={ "class": "input-field", 'placeholder': 'Password Confirmation'}))


class User_Signin_Form(forms.Form):
    username= forms.CharField(label= '', widget=forms.TextInput(attrs={"class": "input-field", 'placeholder': 'John Doe'}))
    password= forms.CharField(label= '', widget=forms.PasswordInput(attrs={ "class": "input-field", 'placeholder': 'Password'}))

    error_messages = {
        'invalid_login': "Please enter a correct username and password."
                           "Note that both fields may be case-sensitive.",
        'inactive': "This account is inactive.",
    }


    def confirm_login_allowed(self, user):          ## Control whether the given User may log in.
        if not user.is_active:     ## If user.is_active == False ... raise ValidationError.
            raise forms.ValidationError(
                self.error_messages['inactive'],
                code='inactive',
            )

    def clean(self):         ## Form Fields Validation.
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')

        if username and password:
            self.user = authenticate(username=username, password=password)
            if self.user is None:
                raise forms.ValidationError(
                    self.error_messages['invalid_login'],
                    code='invalid_login',
                )
            else:
                self.confirm_login_allowed(self.user)
        return self.cleaned_data


    def clean_username(self):
        username = self.cleaned_data.get("username")
        qs = User.objects.filter(username__exact=username)
        if not qs.exists():
            raise forms.ValidationError("This is an invalid user.")
        if qs.count() != 1:
            raise forms.ValidationError("This is an invalid user.")
        return username


class UserForm(forms.ModelForm):
    class Meta:
        model= User
        fields= ['username', 'email', 'first_name', 'last_name']
        widgets= {
        'username': forms.TextInput(attrs= {'class' : 'input-field'}),
        'email': forms.EmailInput(attrs= {'class' : 'input-field'}),
        'first_name': forms.TextInput(attrs= {'class' : 'first_name'}),
        'last_name': forms.TextInput(attrs= {'class' : 'last_name'}),
        }


class ProfileForm(forms.ModelForm):
    avatar = forms.ImageField(label= '')
    class Meta:
        model= Profile
        fields= ['bio', 'birthdate', 'country', 'avatar']
        # exclude= ['user', 'created_at', 'updated_at']

        widgets= {
        'bio': forms.Textarea(attrs= {'class' : 'bio'}),
        'birthdate': forms.SelectDateWidget(attrs= {'class' : 'date'}),
        'country': forms.TextInput(attrs= {'class' : 'input-field'}),
        }

social/templates/social/home.html
{% extends 'base.html' %}
{% load static %}



{% block content %}
<main class= 'container'>
    {% include 'parts/left.html' %}
    {% include 'social/tweet.html' %}

    <section class="main-content">
        <div class="nav">
            <a class="text" href="{% url 'home_page' %}">Home</a>
            <a class="icon" href="#"><img src="{% static 'img/hot-sale.png' %}"></a>
        </div>

        <div class="post-form">
            <div class="user-img">
                {% if user.profile.avatar %}
                    <img src="{{ user.profile.avatar.url }}">
                {% else %}
                    <img src="{% static 'img/add-profile.jfif' %}">
                {% endif %}
            </div>
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.body }}
                <!--<textarea class="post-input" name="" id="" cols="30" rows="10"></textarea>-->
                <label for="id_post_image" class="custom-file-upload">
                    <img src="{% static 'img/add.png' %}" alt="">
                </label>
                {{ form.post_image }}
                <!--<input type="file" name="avatar" accept="image/*" id="id_avatar" class="upload-post-file">-->
                <button class="tweet-btn" type="submit">Tweet</button>
            </form>
        </div>
        <div class="user-tweets">
            {% for post in post_list %}
                <a class="post-card" href="#">
                    <div class="user-img">
                        {% if post.author.avatar %}
                            <img src="{{ post.author.avatar.url }}">
                        {% else %}
                           <img src="{% static 'img/add-profile.jfif' %}">
                        {% endif %}
                    </div>
                    <div class="user-info">
                        <p class="full-name">{{ post.author.first_name }} {{ post.author.last_name }}</p>
                        <p class="username">@{{ post.author.username }}</p>
                        <p class="created-at">{{ post.created_on }}</p>
                    </div>
                    <div class="post-body">
                        <p>{{ post.body }}</p>
                    </div>
                    <div class="post-img">
                        {% for images in post.post_image.all %}
                            <img src="{{ post.post_image.url }}">
                            <!--<img src="{% static 'img/3.jpg' %}" alt="">-->
                        {% endfor %}
                    </div>
                    <div class="icons">
                        <span class= 'far fa-comment'></span>
                        <span class= 'fas fa-retweet'></span>
                        <span class= 'far fa-heart'></span>
                        <span class= 'far fa-share-square'></span>
                    </div>
                </a>
            {% endfor %}
        </div>
    </section>

    {% include 'parts/right.html' %}
</main>
{% endblock content %}

social/templates/social/show_notifications.html
{% load static %}
<div class="dropdown">
    <span class="badge bg-primary notification-badge" style="cursor:pointer;" onclick="ToggleNotifications()">Notifications {{notifications.count}}</span>
    <div class="dropdown-content d-none" id="notification-container">
        {% for notification in notifications %}
            {% if notification.post %}
                {% if notification.notification_type == 1 %}
                    <div class="dropdown-item-parent">
                        <a href="{% url 'post_notification' notification.pk notification.post.pk %}">@{{notification.from_user}} Liked Your Post</a>
                        <span class="dropdown-item-close" style="cursor:pointer;">&times;</span>
                    </div>
                {% elif notification.notification_type == 2 %}
                    <div class="dropdown-item-parent">
                        <a href="{% url 'post_notification' notification.pk notification.post.pk %}">@{{notification.from_user}} Commented on Your Post</a>
                        <span class="dropdown-item-close" style="cursor:pointer;">&times;</span>
                    </div>
                {% endif %}

            {% elif notification.comment %}
                {% if notification.notification_type == 1 %}
                    <div class="dropdown-item-parent">
                        <a href="{% url 'post_notification' notification.pk notification.comment.post.pk %}">@{{notification.from_user}} Liked Your Comment</a>
                        <span class="dropdown-item-close" style="cursor:pointer;">&times;</span>
                    </div>
                {% elif notification.notification_type == 2 %}
                    <div class="dropdown-item-parent">
                        <a href="{% url 'post_notification' notification.pk notification.comment.post.pk %}">@{{notification.from_user}} Replied on Your Comment</a>
                        <span class="dropdown-item-close" style="cursor:pointer;">&times;</span>
                    </div>
                {% endif %}

            {% elif notification.thread %}
                <div class="dropdown-item-parent">
                    <a href="{% url 'thread_notification' notification.pk notification.thread.pk %}">@{{notification.from_user}} Sent a Message</a>
                    <span class="dropdown-item-close" style="cursor:pointer;">&times;</span>
                </div>

            {% else %}
                <div class="dropdown-item-parent">
                    <a href="{% url 'follow_notification' notification.pk notification.from_user.profile.profile_pk %}">@{{notification.from_user}} Following You Now</a>
                    <span class="dropdown-item-close" style="cursor:pointer;">&times;</span>
                </div>
            {% endif %}
        {% endfor %}
    </div>
</div>

social/templates/social/tweet.html
{% load static %}


<section id="tweet-box" class="tweet-page hidden">
    <div class="wrapper">
        <div class="form-box">
            <span id="tweet-cancel-btn" class="cancel-btn fas fa-times"></span>
            <div class="user-img">
                <img src="{% static 'img/add-profile.jfif' %}">
            </div>
            <form method="POST" enctype="multipart/form-data">
                <div class="input-box">
                    <textarea class="post-input"></textarea>
                </div>
                <label for="id_post_image" class="custom-file-upload">
                    <img src="{% static 'img/add.png' %}">
                </label>
                <input type="file" name="avatar" accept="image/*" id="id_post_image" class="upload-post-file">
                <div class="btn-box">
                    <button class="tweet-btn" type="submit">Tweet</button>
                </div>
            </form>
        </div>
    </div>
</section>